id: I3C4F5051
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T22:40:33+00:00'
last_modified: '2022-06-10T05:10:31.937313+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20129
  title: རྟ་ནག་སྒྲོག་འགྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E37E:
      image_group_id: I1KG14902
      title: Volume 1 of rta nag sgrog 'gros
      total_pages: 562
      order: 1
      base_file: E37E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
