id: P000399
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20129
  title: རྟ་ནག་སྒྲོག་འགྲོས།
  author: ''
  volumes:
    7ad258322d1548f39d7b40965d89ada8:
      image_group_id: I1KG14902
      title: Volume 1 of rta nag sgrog 'gros
      volume_number: 1
      total_pages: 562
      base_file: v001.txt
